var http = require('http');
var fs = require('fs');
var xss = require('xss-clean');
var path = require('path');
var express = require('express');
var bodyParser = require('body-parser');
const swaggerUi = require('swagger-ui-express');
var api = require('./routes/api.js');
const swaggerDocument = require('./swagger.json');
var app = express();
var cors = require('cors');
app.use(bodyParser.json({ limit: "50mb" }));
app.use(bodyParser.urlencoded({ limit: "50mb", extended: true, parameterLimit: 50000 }));
app.use(cors());
app.use(xss());
app.use('/api',api);
app.use("/userfiles", express.static(__dirname + '/public/users'));
app.use("/pharmacy-files", express.static(__dirname + '/public/pharmacy-products'));
app.use("/lab-tests", express.static(__dirname + '/public/lab-tests'));
app.use("/blog-files", express.static(__dirname + '/public/blog'));
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument));
app.listen(process.env.PORT || 5000);
console.log("App is listening at PORT 5000");